# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node-terminal-emulator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: yarn
    - name: Build
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: yarn build
    - name: Test
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        script: yarn test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: junit.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: '**/*', '!src/**', '!node_modules/**'
        if-no-files-found: error
        retention-days: 5
